### PR TITLE
Small message changes.

### PR DESCRIPTION
**Pull request by WoahMikel**

### CODE REVIEW

**Review by PhanaticD — COMMENTED** [review]
we dont use those prefixes since we use essentials chat, and I really dont see how the day and night changes are needed at all

**Comment by WoahMikel** [comment]
The prefixes in the file I edited are used in the {ELEMENT} placeholder. Another thing to note is that {ELEMENTCOLOR} is not needed if you use the prefixes. {ELEMENT} already should hold the colors if I'm correct.

**Comment by PhanaticD** [comment]
still I am not seeing why that is needed

**Comment by WoahMikel** [comment]
It is not, this was just a small message change. I'll work on other things instead, though.

**Pull request closed without merging**
